## Redis 配置
spring:
  redis:
  ## Redis服务器连接密码（默认为空）
    password: safedog@2017
    ## Redis服务器地址
    host: 192.168.100.33
    ## Redis服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 5000

  output:
    ansi:
      enabled: always
logging:
  file: src/main/resources/log/spring-boot.log
  config: classpath:spring-logback.xml
  pattern:
    level:
    file:
#    console: '%clr(%d{HH:mm:ss}){yellow} [%clr(%thread){red}] %-5level --- %clr(%logger){green} | %msg%n'
